
import React from 'react';
import { 
  AppWindow, 
  Settings, 
  Calculator, 
  CloudSun, 
  StickyNote, 
  Image as ImageIcon, 
  Flame,
  BadgeDollarSign,
  Music4,
  Library,
  Repeat,
  Type,
  KeyRound,
  BadgePercent,
  RefreshCcw,
  Clapperboard,
  BarChart3,
  Briefcase,
  TrendingUp,
  Palette,
  Crown,
  ListTodo,
  PenTool,
  Megaphone,
  Gamepad2,
  ListMusic,
  Award,
  Heart,
  Lightbulb,
  Gem,
  Crosshair,
  Mic,
  Film
} from 'lucide-react';
import { AppConfig, AppID } from './types';

export const ALL_APPS: Record<AppID, AppConfig> = {
  [AppID.STORE]: {
    id: AppID.STORE,
    name: 'App Store',
    icon: AppWindow,
    color: 'from-blue-500 to-blue-600',
    description: 'Discover and install new tools.',
    isSystem: true,
  },
  [AppID.TIPS]: {
    id: AppID.TIPS,
    name: 'Tips',
    icon: Lightbulb,
    color: 'from-yellow-400 to-amber-500',
    description: 'User guide and documentation.',
    isSystem: true,
  },
  [AppID.PASSWORDS]: {
    id: AppID.PASSWORDS,
    name: 'Passwords',
    icon: KeyRound,
    color: 'from-neutral-600 to-neutral-800',
    description: 'Securely manage credentials.',
    isSystem: true,
  },
  [AppID.CAREER_AI]: {
    id: AppID.CAREER_AI,
    name: 'CareerAI',
    icon: Briefcase,
    color: 'from-sky-600 to-cyan-700',
    description: 'Build your career portfolio with AI.',
    isSystem: false,
  },
  [AppID.TRENDS_AI]: {
    id: AppID.TRENDS_AI,
    name: 'TrendsAI',
    icon: TrendingUp,
    color: 'from-purple-600 to-indigo-700',
    description: 'Track, search, and analyze viral trends.',
    isSystem: false,
  },
  [AppID.ANALYTICS_AI]: {
    id: AppID.ANALYTICS_AI,
    name: 'AnalyticsAI',
    icon: BarChart3,
    color: 'from-emerald-500 to-green-600',
    description: 'Music revenue dashboard & parser.',
    isSystem: false,
  },
  [AppID.MARKUP_AI]: {
    id: AppID.MARKUP_AI,
    name: 'MarkupAI',
    icon: BadgePercent,
    color: 'from-fuchsia-500 to-rose-500',
    description: 'Find affiliate & white label arbitrage opportunities.',
    isSystem: false,
  },
  [AppID.CONTENT_AI]: {
    id: AppID.CONTENT_AI,
    name: 'ContentAI',
    icon: Clapperboard,
    color: 'from-red-600 to-rose-600',
    description: 'TV-style content arc generator.',
    isSystem: false,
  },
  [AppID.CONVERT_AI]: {
    id: AppID.CONVERT_AI,
    name: 'ConvertAI',
    icon: RefreshCcw,
    color: 'from-orange-500 to-amber-500',
    description: 'Local file conversion utility.',
    isSystem: false,
  },
  [AppID.CALCULATOR]: {
    id: AppID.CALCULATOR,
    name: 'Calculator',
    icon: Calculator,
    color: 'from-orange-400 to-orange-500',
    description: 'Perform basic calculations.',
    isSystem: false,
  },
  [AppID.WEATHER]: {
    id: AppID.WEATHER,
    name: 'Weather',
    icon: CloudSun,
    color: 'from-sky-400 to-blue-500',
    description: 'Check the forecast.',
    isSystem: false,
  },
  [AppID.NOTES]: {
    id: AppID.NOTES,
    name: 'Notes',
    icon: StickyNote,
    color: 'from-yellow-400 to-yellow-500',
    description: 'Capture your thoughts.',
    isSystem: false,
  },
  [AppID.PHOTOS]: {
    id: AppID.PHOTOS,
    name: 'Photos',
    icon: ImageIcon,
    color: 'from-pink-400 via-red-400 to-yellow-400',
    description: 'View your memories.',
    isSystem: false,
  },
  [AppID.SETTINGS]: {
    id: AppID.SETTINGS,
    name: 'Settings',
    icon: Settings,
    color: 'from-slate-500 to-slate-600',
    description: 'System preferences.',
    isSystem: true,
  },
  [AppID.DRAMA]: {
    id: AppID.DRAMA,
    name: 'Drama Tracker',
    icon: Flame,
    color: 'from-red-500 via-orange-500 to-purple-600',
    description: 'Track online rumors and timelines.',
    isSystem: false,
  },
  [AppID.SELL_IT]: {
    id: AppID.SELL_IT,
    name: 'Just Sell It',
    icon: BadgeDollarSign,
    color: 'from-emerald-400 to-teal-600',
    description: 'Generate high-converting sales strategies.',
    isSystem: false,
  },
  [AppID.LYRICS_AI]: {
    id: AppID.LYRICS_AI,
    name: 'LyricsAI',
    icon: Music4,
    color: 'from-violet-500 to-fuchsia-500',
    description: 'Advanced music literature analysis.',
    isSystem: false,
  },
  [AppID.ALBUMS_AI]: {
    id: AppID.ALBUMS_AI,
    name: 'AlbumsAI',
    icon: Library,
    color: 'from-blue-500 to-indigo-500',
    description: 'Organize analyzed songs into projects.',
    isSystem: false,
  },
  [AppID.LINK_FLIPPER]: {
    id: AppID.LINK_FLIPPER,
    name: 'LinkFlipper',
    icon: Repeat,
    color: 'from-cyan-500 to-blue-600',
    description: 'Convert YouTube Shorts to regular watch links.',
    isSystem: false,
  },
  [AppID.CAPTIONS]: {
    id: AppID.CAPTIONS,
    name: 'CaptionsAI',
    icon: Type,
    color: 'from-fuchsia-600 to-purple-600',
    description: 'Generate and train platform-specific captions.',
    isSystem: false,
  },
  [AppID.WALLPAPER_AI]: {
    id: AppID.WALLPAPER_AI,
    name: 'WallpaperAI',
    icon: Palette,
    color: 'from-pink-500 to-rose-500',
    description: 'Generate 4K wallpapers for your devices.',
    isSystem: false,
  },
  [AppID.GET_FAMOUS]: {
    id: AppID.GET_FAMOUS,
    name: 'Get Famous',
    icon: Crown,
    color: 'from-yellow-400 via-amber-500 to-orange-600',
    description: 'Tactical fame roadmap generator.',
    isSystem: false,
  },
  [AppID.PRIORITY_AI]: {
    id: AppID.PRIORITY_AI,
    name: 'PriorityAI',
    icon: ListTodo,
    color: 'from-cyan-500 to-teal-500',
    description: 'Stop overthinking. Generate action plans.',
    isSystem: false,
  },
  [AppID.BRAND_KIT_AI]: {
    id: AppID.BRAND_KIT_AI,
    name: 'BrandKitAI',
    icon: PenTool,
    color: 'from-gray-700 to-slate-900',
    description: 'Instant brand identity generator.',
    isSystem: false,
  },
  [AppID.VIRAL_PLAN_AI]: {
    id: AppID.VIRAL_PLAN_AI,
    name: 'ViralPlanAI',
    icon: Megaphone,
    color: 'from-orange-600 to-pink-600',
    description: 'Automated UGC and Content ID strategy planner.',
    isSystem: false,
  },
  [AppID.AI_PLAYGROUND]: {
    id: AppID.AI_PLAYGROUND,
    name: 'AI Playground',
    icon: Gamepad2,
    color: 'from-emerald-400 via-teal-500 to-lime-500',
    description: 'Gamified AI experiments & widgets.',
    isSystem: false,
  },
  [AppID.PLAYLIST_AI]: {
    id: AppID.PLAYLIST_AI,
    name: 'PlaylistAI',
    icon: ListMusic,
    color: 'from-green-500 to-emerald-600',
    description: 'Generative playlist curator for DSPs.',
    isSystem: false,
  },
  [AppID.ACHIEVEMENTS]: {
    id: AppID.ACHIEVEMENTS,
    name: 'Achievements',
    icon: Award,
    color: 'from-yellow-500 to-amber-500',
    description: 'Generate milestone awards for music streams.',
    isSystem: false,
  },
  [AppID.NSFW_AI]: {
    id: AppID.NSFW_AI,
    name: 'NSFWAI',
    icon: Heart,
    color: 'from-red-700 to-pink-600',
    description: 'Revenue strategy & persona design for adult creators.',
    isSystem: false,
  },
  [AppID.TRAP_AI]: {
    id: AppID.TRAP_AI,
    name: 'TrapAI',
    icon: Gem,
    color: 'from-indigo-600 to-blue-900',
    description: 'Generate luxury trap bars and punchlines.',
    isSystem: false,
  },
  [AppID.OPERATOR]: {
    id: AppID.OPERATOR,
    name: 'Operator',
    icon: Crosshair,
    color: 'from-gray-800 to-black',
    description: 'Linear task execution interface.',
    isSystem: false,
  },
  [AppID.SPEECH_AI]: {
    id: AppID.SPEECH_AI,
    name: 'SpeechAI',
    icon: Mic,
    color: 'from-sky-500 to-blue-600',
    description: 'Text-to-Speech synthesizer with emotion control.',
    isSystem: false,
  },
  [AppID.SHORTS_STUDIO]: {
    id: AppID.SHORTS_STUDIO,
    name: 'Shorts Studio',
    icon: Film,
    color: 'from-red-600 to-pink-600',
    description: 'Generate viral videos and thumbnails with Veo.',
    isSystem: false,
  }
};

export const INITIAL_INSTALLED_APPS: AppID[] = [
  AppID.TIPS,
  AppID.STORE,
  AppID.PASSWORDS,
  AppID.OPERATOR,
  AppID.SHORTS_STUDIO,
  AppID.SPEECH_AI,
  AppID.MARKUP_AI,
  AppID.CONTENT_AI,
  AppID.ANALYTICS_AI,
  AppID.CAREER_AI,
  AppID.TRENDS_AI,
  AppID.WALLPAPER_AI,
  AppID.GET_FAMOUS,
  AppID.PRIORITY_AI,
  AppID.BRAND_KIT_AI,
  AppID.VIRAL_PLAN_AI,
  AppID.AI_PLAYGROUND,
  AppID.PLAYLIST_AI,
  AppID.ACHIEVEMENTS,
  AppID.NSFW_AI,
  AppID.TRAP_AI,
  AppID.CONVERT_AI,
  AppID.SETTINGS,
  AppID.DRAMA,
  AppID.SELL_IT,
  AppID.LYRICS_AI,
  AppID.ALBUMS_AI,
  AppID.LINK_FLIPPER,
  AppID.CAPTIONS
];

export interface Wallpaper {
  id: string;
  name: string;
  style: React.CSSProperties;
  thumbnail: string;
}

export const WALLPAPERS: Wallpaper[] = [
  {
    id: 'ios18',
    name: 'iOS 18 Mesh',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=400&q=80',
    style: {
      backgroundImage: 'url(https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1920&q=100)',
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    }
  },
  {
    id: 'titanium',
    name: 'Natural Titanium',
    thumbnail: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=400&q=80',
    style: {
      backgroundImage: 'url(https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1920&q=100)',
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    }
  },
  {
    id: 'deepspace',
    name: 'Deep Space',
    thumbnail: 'https://images.unsplash.com/photo-1464802686167-b939a6910659?auto=format&fit=crop&w=400&q=80',
    style: {
      backgroundImage: 'url(https://images.unsplash.com/photo-1464802686167-b939a6910659?auto=format&fit=crop&w=1920&q=100)',
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    }
  },
  {
    id: 'mountain',
    name: 'Alpine Mist',
    thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=400&q=80',
    style: {
      backgroundImage: 'url(https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1920&q=100)',
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    }
  },
  {
    id: 'sunset',
    name: 'Golden Coast',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80',
    style: {
      backgroundImage: 'url(https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1920&q=100)',
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    }
  },
  {
    id: 'minimal',
    name: 'Pro Graphite',
    thumbnail: 'https://images.unsplash.com/photo-1557683311-eac922347aa1?auto=format&fit=crop&w=400&q=80',
    style: {
      backgroundImage: 'url(https://images.unsplash.com/photo-1557683311-eac922347aa1?auto=format&fit=crop&w=1920&q=100)',
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    }
  }
];
