
import { Type } from "@google/genai";
import { getAIClient, APP_MODEL_CONFIG, normalizeAiJson } from "./core";
import { AppID } from "../../types";

export interface ShortConcept {
  id: string;
  title: string;
  visualPrompt: string;
  niche: string;
  style: string;
}

export const generateShortsConcepts = async (
  niche: string, 
  accountName: string, 
  audioContext: string
): Promise<ShortConcept[]> => {
  const ai = getAIClient();
  const systemInstruction = `You are a viral content strategist for a burner account named "@${accountName}".
  Niche: ${niche}.
  Audio/Pacing Requirements: ${audioContext || "Standard viral pacing"}.
  
  Task: Generate 3 distinct video concepts that can be generated by AI video models (Veo).
  The 'visualPrompt' must be descriptive, focused on movement and aesthetics, suitable for a video generation model.
  Keep prompts under 40 words. Focus on visual loops, satisfying motion, or atmospheric scenes.`;

  const responseSchema = {
    type: Type.OBJECT,
    properties: {
      concepts: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            title: { type: Type.STRING },
            visualPrompt: { type: Type.STRING }
          },
          required: ['title', 'visualPrompt']
        }
      }
    },
    required: ['concepts']
  };

  const response = await ai.models.generateContent({
    model: APP_MODEL_CONFIG[AppID.SHORTS_STUDIO],
    contents: "Generate 3 video concepts.",
    config: {
      systemInstruction,
      responseMimeType: "application/json",
      responseSchema
    }
  });

  const data = await normalizeAiJson<{ concepts: Array<{ title: string; visualPrompt: string }> }>(
    response.text || '',
    responseSchema
  );
  return (data.concepts || []).map((c: any) => ({
    ...c,
    id: Date.now().toString() + Math.random().toString().slice(2, 5),
    niche,
    style: niche // Use niche as style for continuity
  }));
};

export const generateShortsThumbnail = async (prompt: string, style: string): Promise<string | null> => {
  const ai = getAIClient();
  const fullPrompt = `${prompt}. Style: ${style}. High quality, 9:16 vertical ratio, eye-catching YouTube Shorts thumbnail.`;

  const response = await ai.models.generateContent({
    model: APP_MODEL_CONFIG['shorts_studio_image'], // gemini-2.5-flash-image
    contents: {
      parts: [{ text: fullPrompt }]
    },
    config: {
      imageConfig: {
        aspectRatio: "9:16" // Vertical for Shorts
      }
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }
  return null;
};

export const generateShortsVideo = async (prompt: string, style: string, audioContext: string): Promise<string | null> => {
  const ai = getAIClient();
  const fullPrompt = `${prompt}. Niche/Style: ${style}. Audio Cues: ${audioContext}. Cinematic, high motion, 720p quality.`;

  // Veo Video Generation
  let operation = await ai.models.generateVideos({
    model: APP_MODEL_CONFIG['shorts_studio_video'], // veo-3.1-fast-generate-preview
    prompt: fullPrompt,
    config: {
      numberOfVideos: 1,
      resolution: '720p',
      aspectRatio: '9:16'
    }
  });

  // Polling loop
  while (!operation.done) {
    await new Promise(resolve => setTimeout(resolve, 5000)); // Poll every 5s
    operation = await ai.operations.getVideosOperation({ operation: operation });
  }

  const videoUri = operation.response?.generatedVideos?.[0]?.video?.uri;
  return videoUri || null;
};
