
import { Type } from "@google/genai";
import { APP_MODEL_CONFIG, generateAIContent, generateAIVideo } from "./core";
import { getArray, getString, mapRecordArray, parseJsonObject } from "./parse";
import { AppID } from "../../types";

export interface ShortConcept {
  id: string;
  title: string;
  visualPrompt: string;
  niche: string;
  style: string;
}

export const generateShortsConcepts = async (
  niche: string, 
  accountName: string, 
  audioContext: string
): Promise<ShortConcept[]> => {
  const systemInstruction = `You are a viral content strategist for a burner account named "@${accountName}".
  Niche: ${niche}.
  Audio/Pacing Requirements: ${audioContext || "Standard viral pacing"}.
  
  Task: Generate 3 distinct video concepts that can be generated by AI video models (Veo).
  The 'visualPrompt' must be descriptive, focused on movement and aesthetics, suitable for a video generation model.
  Keep prompts under 40 words. Focus on visual loops, satisfying motion, or atmospheric scenes.`;

  const response = await generateAIContent({
    model: APP_MODEL_CONFIG[AppID.SHORTS_STUDIO],
    contents: "Generate 3 video concepts.",
    config: {
      systemInstruction,
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          concepts: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                title: { type: Type.STRING },
                visualPrompt: { type: Type.STRING }
              },
              required: ['title', 'visualPrompt']
            }
          }
        },
        required: ['concepts']
      }
    }
  });

  const data = parseJsonObject(response.text);
  if (!data) return [];
  return mapRecordArray(getArray(data, "concepts")).map((concept) => ({
    title: getString(concept, "title", "Untitled"),
    visualPrompt: getString(concept, "visualPrompt", ""),
    id: Date.now().toString() + Math.random().toString().slice(2, 5),
    niche,
    style: niche // Use niche as style for continuity
  })).filter((concept) => concept.visualPrompt.length > 0);
};

export const generateShortsThumbnail = async (prompt: string, style: string): Promise<string | null> => {
  const fullPrompt = `${prompt}. Style: ${style}. High quality, 9:16 vertical ratio, eye-catching YouTube Shorts thumbnail.`;

  const response = await generateAIContent({
    model: APP_MODEL_CONFIG['shorts_studio_image'], // gemini-2.5-flash-image
    contents: {
      parts: [{ text: fullPrompt }]
    },
    config: {
      imageConfig: {
        aspectRatio: "9:16" // Vertical for Shorts
      }
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }
  return null;
};

export const generateShortsVideo = async (prompt: string, style: string, audioContext: string): Promise<string | null> => {
  const fullPrompt = `${prompt}. Niche/Style: ${style}. Audio Cues: ${audioContext}. Cinematic, high motion, 720p quality.`;

  // Veo Video Generation
  const result = await generateAIVideo({
    model: APP_MODEL_CONFIG['shorts_studio_video'], // veo-3.1-fast-generate-preview
    prompt: fullPrompt,
    config: {
      numberOfVideos: 1,
      resolution: '720p',
      aspectRatio: '9:16'
    }
  });

  return result.proxyUrl;
};
